### ISSUE TITLE
why python

### ISSUE THREAD

**Issue by oliver-ni** [thegithubgeek/Handwriting-Recognizer#1]
???

**Comment by frankxwang** [comment]
Cuz numpy use python

**Comment by oliver-ni** [comment]
no

use java

its better

**Comment by oliver-ni** [comment]
did you start already?

**Comment by oliver-ni** [comment]
how much did u do

**Comment by kongriley** [comment]
it's fine, numpy is easier
if you _really_ want to do java then go ahead, it's just gonna be harder just saying

**Comment by oliver-ni** [comment]
Lmao I was dumb
